# Travis CI 설정
language: java
jdk:
  - openjdk8

branches:
  only:
    - main
# Travis CI 서버의 Home
before_install:
  - chmod +x gradlew

# travis ci 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # deploy로 이동 후 전체 압축
  - cd ../ &&mkdir -p deploy # 상위 디렉토리 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/lifium-springboot-webservice.zip # deploy로 zip 파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webservice-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main # main branch 허용

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webservice-springboot-build # S3 버킷
    key: lifium-springboot-webservice.zip
    bundle_type: zip
    application: lifium-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: lifium-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main # main branch 허용
      # s3 연결 시에도 main 브랜치에서 할 수 있도록 on: branch: main을 적어줬듯이
      # codedeploy 시에도 main 브랜치에서 실행하라고 명시해주지 않아서 codedeploy trigger가 발생하지 않아 생긴 문제였다.
      # 자그만치 2시간 넘게 까먹음...

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - gomljo0307@naver.com