language: java
jdk:
  - openjdk8

branches:
  only:
    - gomljo

# travis ci 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'gomljo0307@naver.com'